src/java/entity/Register.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package entity;

import java.sql.Timestamp;

/**
 *
 * @author taina
 */
public class Register {

    private Timestamp dateStart, dateEnd;
    private User user;
    private Subject subject;
    private PricePackage pricePackage;
    private double SalePrice;
    private int PriceRate;
    private Boolean status;

    public Register() {
    }

    public Register(Timestamp dateStart, Timestamp dateEnd, User user, Subject subject, PricePackage pricePackage, double SalePrice, int PriceRate) {
        this.dateStart = dateStart;
        this.dateEnd = dateEnd;
        this.user = user;
        this.subject = subject;
        this.pricePackage = pricePackage;
        this.SalePrice = SalePrice;
        this.PriceRate = PriceRate;
    }

    public Boolean getStatus() {
        return status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }
    
    public Timestamp getDateStart() {
        return dateStart;
    }

    public void setDateStart(Timestamp dateStart) {
        this.dateStart = dateStart;
    }
    
    public String getDateStartAgo() {
        return MyMethod.getTimeAgo(MyMethod.getT_now(), dateStart);
    }

    public Timestamp getDateEnd() {
        return dateEnd;
    }

    public void setDateEnd(Timestamp dateEnd) {
        this.dateEnd = dateEnd;
    }
    
    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public Subject getSubject() {
        return subject;
    }

    public void setSubject(Subject subject) {
        this.subject = subject;
    }

    public PricePackage getPricePackage() {
        return pricePackage;
    }

    public void setPricePackage(PricePackage pricePackage) {
        this.pricePackage = pricePackage;
    }

    public double getSalePrice() {
        return SalePrice;
    }

    public void setSalePrice(double SalePrice) {
        this.SalePrice = SalePrice;
    }

    public int getPriceRate() {
        return PriceRate;
    }

    public void setPriceRate(int PriceRate) {
        this.PriceRate = PriceRate;
    }
    
    
    
}

src/java/controller/sale/NewServlet.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controller.sale;

import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 *
 * @author Nguyen Van Long
 */
@WebServlet(name = "NewServlet", urlPatterns = {"/NewServlet"})
public class NewServlet extends HttpServlet {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        try (PrintWriter out = response.getWriter()) {
            /* TODO output your page here. You may use following sample code. */
            out.println("<!DOCTYPE html>");
            out.println("<html>");
            out.println("<head>");
            out.println("<title>Servlet NewServlet</title>");            
            out.println("</head>");
            out.println("<body>");
            out.println("<h1>Servlet NewServlet at " + request.getContextPath() + "</h1>");
            out.println("</body>");
            out.println("</html>");
        }
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

src/java/controller/sale/RegistrationsDetailServlet.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controller.sale;

import dao.PricePackageDAO;
import dao.RegisterDAO;
import entity.PricePackage;
import entity.Register;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 *
 * @author xuant
 */
public class RegistrationsDetailServlet extends HttpServlet {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        try (PrintWriter out = response.getWriter()) {
            /* TODO output your page here. You may use following sample code. */
            out.println("<!DOCTYPE html>");
            out.println("<html>");
            out.println("<head>");
            out.println("<title>Servlet RegistrationsDetailServlet</title>");            
            out.println("</head>");
            out.println("<body>");
            out.println("<h1>Servlet RegistrationsDetailServlet at " + request.getContextPath() + "</h1>");
            out.println("</body>");
            out.println("</html>");
        }
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        RegisterDAO rdao = new RegisterDAO();
        PricePackageDAO packageDAO = new PricePackageDAO();
        int userId = Integer.parseInt(request.getParameter("userId"));
        int subjectId = Integer.parseInt(request.getParameter("subjectId"));
        Register register = rdao.getRegister(rdao.getConnection(), userId, subjectId);
        List<PricePackage> all = packageDAO.getAll();
        request.setAttribute("register", register);
        request.setAttribute("all", all);
        
        request.getRequestDispatcher("../../view/sale/registrationsDetail.jsp").forward(request, response);
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

src/java/controller/sale/RegistrationsListServlet.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controller.sale;

import dao.RegisterDAO;
import entity.Register;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 *
 * @author xuant
 */
public class RegistrationsListServlet extends HttpServlet {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        String url = request.getRequestURI();
        RegisterDAO rdao = new RegisterDAO();
        List<Register> registers = rdao.getAll();
        request.setAttribute("registers", registers);
        if (url.contains("/registrations")) {
            request.getRequestDispatcher("../view/sale/registrations.jsp").forward(request, response);
        } else {
            request.getRequestDispatcher("/view/sale/registrations.jsp").forward(request, response);
        }
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

web/view/sale/registrationsDetail.jsp
<!------ Include the above in your HEAD tag ---------->




<%@page contentType="text/html" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>


<html lang="en">

    <jsp:include page="../component/common/head.jsp" />

    <style>
        .form-group {
            display: flex;
            align-items: center;
            font-size: 20px;
            justify-content: center;
        }

        .control-label {
            width: 340px;
        }

        #featured {
            width: 20px;
            height: 20px;
        }

        .form-horizontal {
            color: rgb(33 40 50);
            font-weight: 500;
        }
    </style>

    <body>

        <div class="main-wrapper main-wrapper-02">
            <jsp:include page="../component/administration/header.jsp" />
            <!-- Courses Admin Start -->
            <div class="section overflow-hidden position-relative" id="wrapper">

                <!-- Sidebar Wrapper Start -->
                <div class="sidebar-wrapper">
                    <div class="menu-list">
                        <a class="active" href="courses-admin.html"><img
                                src="../../assets/images/menu-icon/icon-1.png" alt="Icon"></a>
                        <a href="messages.html"><img src="../../assets/images/menu-icon/icon-2.png"
                                                     alt="Icon"></a>
                        <a href="overview.html"><img src="../../assets/images/menu-icon/icon-3.png"
                                                     alt="Icon"></a>
                        <a href="engagement.html"><img src="../../assets/images/menu-icon/icon-4.png"
                                                       alt="Icon"></a>
                        <a href="traffic-conversion.html"><img src="../../assets/images/menu-icon/icon-5.png"
                                                               alt="Icon"></a>
                    </div>
                </div>
                <!-- Sidebar Wrapper End -->

                <!-- Page Content Wrapper Start -->
                <div class="page-content-wrapper">
                    <div class="container-fluid custom-container">

                        <!-- Message Start -->

                        <!-- Message End -->




                        <div class="right">



                            





                                <!-- Text input-->
                                <div class="form-group">
                                    <label class="col-md-4 control-label" for="subject_name">SUBJECT
                                        NAME</label>
                                    <div class="single-form  col-md-4">
                                        <input id="subject_name" name="subject_name" placeholder="SUBJECT NAME"
                                               class="form-control input-md" value="${register.subject.title}"
                                               type="text" readonly>
                                        <div id="subject_name-error"></div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-md-4 control-label" for="subject_name">PACKAGE
                                        NAME</label>
                                    <div class="single-form  col-md-4">
                                        <input id="subject_name" name="subject_name" placeholder="SUBJECT NAME"
                                               class="form-control input-md" value="${register.pricePackage.name}"
                                               type="text" readonly>
                                        <div id="subject_name-error"></div>
                                    </div>
                                </div>

                                <!-- Text input Listed Price-->
                                <div class="form-group" style="margin-top: 20px">
                                    <label class="col-md-4 control-label" for="listedPrice">LISTED PRICE</label>
                                    <div class="single-form col-md-4">
                                        <input id="listedPrice" name="listedPrice" placeholder="LISTED PRICE"
                                               class="form-control input-md" type="number"
                                               value="${register.subject.listedPrice}" readonly>
                                        <div id="listedPrice-error"></div>
                                    </div>
                                </div>

                                <!-- Text input Listed Price-->
                                <div class="form-group" style="margin-top: 20px">
                                    <label class="col-md-4 control-label" for="listedPrice">SALE PRICE</label>
                                    <div class="single-form col-md-4">
                                        <input id="listedPrice" name="listedPrice" placeholder="LISTED PRICE"
                                               class="form-control input-md" type="number"
                                               value="${register.subject.salePrice}" readonly>
                                        <div id="listedPrice-error"></div>
                                    </div>
                                </div>        

                                <div class="form-group">
                                    <label class="col-md-4 control-label" for="subject_name">FULL
                                        NAME</label>
                                    <div class="single-form  col-md-4">
                                        <input id="subject_name" name="subject_name" placeholder="SUBJECT NAME"
                                               class="form-control input-md" value="${register.user.name}"
                                               type="text" readonly>
                                        <div id="subject_name-error"></div>
                                    </div>
                                </div>

                                <!-- Select Basic -->
                                <div class="form-group courses-select">
                                    <label class="col-md-4 control-label" for="subject_category">GENDER</label>
                                    <div class="single-form col-md-4">
                                        <input id="subject_name" name="subject_name" placeholder="SUBJECT NAME"
                                               class="form-control input-md" value="${register.user.getGender() ? 'Male' : 'Female'}"
                                               type="text" readonly>

                                    </div>
                                </div>               

                                <div class="form-group">
                                    <label class="col-md-4 control-label" >EMAIL</label>
                                    <div class="single-form  col-md-4">
                                        <input id="" name="" 
                                               class="form-control input-md" value="${register.user.email}"
                                               type="text" readonly>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-4 control-label">PHONE</label>
                                    <div class="single-form  col-md-4">
                                        <input id="1" name="1" 
                                               class="form-control input-md" value="${register.user.phone}"
                                               type="text" readonly>
                                    </div>
                                </div>   



                                <div class="form-group">
                                    <label class="col-md-4 control-label" >VALID FROM</label>
                                    <div class="single-form  col-md-4">
                                        <input id="" name="" 
                                               class="form-control input-md" value="${register.dateStart}"
                                               type="text" readonly>
                                    </div>
                                </div>   

                                <div class="form-group">
                                    <label class="col-md-4 control-label" >VALID TO</label>
                                    <div class="single-form  col-md-4">
                                        <input id="" name="" 
                                               class="form-control input-md" value="${register.dateEnd == null ?'Lifetime':register.dateEnd}"
                                               type="text" readonly>
                                    </div>
                                </div>              





















                                <!-- Select Basic 
                                <div class="form-group courses-select">
                                    <label class="col-md-4 control-label" for="status">GENDER</label>
                                    <div class="single-form col-md-4">
                                        <select id="status" name="status" class="form-control">

                                            <option value="1">Male</option>
                                            <option value="0">Female</option>
                                        </select>
                                        <div id="status-error"></div>
                                    </div>
                                </div>
                                -->





                                
                                <div class="form-group">
                                    <label class="col-md-4 control-label" for="singlebutton"></label>
                                    <div class="single-form col-md-4">
                                        <button id="singlebutton" name="singlebutton"
                                                class="btn btn-primary"
                                                onclick="location.href='${pageContext.request.contextPath}/sale/registrations';"/>Back</button>

                                    </div>
                                </div>




                            
                        </div>









                        <!-- Admin Courses Tab Start -->

                        <!-- Admin Courses Tab End -->

                        <!-- Admin Courses Tab Content Start -->

                        <!-- Admin Courses Tab Content End -->

                        <!-- Courses Resources Start -->
                        <jsp:include page="../component/administration/courses-resources.jsp" />

                        <!-- Courses Resources End -->

                    </div>
                </div>
                <!-- Page Content Wrapper End -->

            </div>
            <!-- Courses Admin End -->






            <jsp:include page="../component/common/footer.jsp" />

            <!--Back To Start-->
            <a href="#" class="back-to-top">
                <i class="icofont-simple-up"></i>
            </a>
            <!--Back To End-->

        </div>

        <!-- JS
============================================ -->
        <jsp:include page="../component/common/js.jsp" />
        <script>
            ClassicEditor
                    .create(document.querySelector('#subject_description'), {
                        // toolbar: [ 'heading', '|', 'bold', 'italic', 'link' ]
                    })
                    .then(editor => {
                        window.editor = editor;
                    })
                    .catch(err => {
                        console.error(err.stack);
                    });
        </script>
    </body>

</html>